POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "password123"
}
### Create a Blog as Test User
GET http://localhost:3003/api/blogs